version: '3.4'

services:
  gatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"

  ordersapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7001:80"

  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002:80"



